### Получить CSRF-токен
GET http://localhost:8080/csrf
Accept: application/json

> {%
   client.global.set("csrfToken", response.body.token);
   client.global.set("csrfHeaderName", response.body.headerName);
%}

### Регистрация пользователя (с CSRF в заголовке)
POST http://localhost:8080/register
Content-Type: application/json
{{csrfHeaderName}}: {{csrfToken}}
Cookie: {{response.headers['Set-Cookie']}}

{
  "username": "test@example.com",
  "password": "password",
  "firstName": "John",
  "lastName": "Doe",
  "phone": "+7 (999) 123-45-67",
  "role": "USER"
}

### Логин
POST http://localhost:8080/login
Content-Type: application/json
{{csrfHeaderName}}: {{csrfToken}}

{
  "username": "test@example.com",
  "password": "password"
}

### Получить свои объявления
GET http://localhost:8080/ads/me
Authorization: Basic test@example.com password

### Получить информацию о себе
GET http://localhost:8080/users/me
Authorization: Basic test@example.com password

### Создать объявление
POST http://localhost:8080/ads
Content-Type: application/json
{{csrfHeaderName}}: {{csrfToken}}
Authorization: Basic test@example.com password

{
  "title": "Ноутбук",
  "price": 25000,
  "description": "Продам ноутбук, состояние отличное"
}